version: 2
updates:
  # Enable version updates for npm (root)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 5
    assignees:
      - "your-username" # Replace with actual username
    reviewers:
      - "your-username" # Replace with actual username
    commit-message:
      prefix: "⬆️ deps"
      include: "scope"
    labels:
      - "dependencies"
      - "automerge"

  # Enable version updates for npm (frontend)
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 5
    assignees:
      - "your-username" # Replace with actual username
    reviewers:
      - "your-username" # Replace with actual username
    commit-message:
      prefix: "⬆️ deps(frontend)"
      include: "scope"
    labels:
      - "dependencies"
      - "frontend"
      - "automerge"

  # Enable version updates for npm (backend)
  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 5
    assignees:
      - "your-username" # Replace with actual username
    reviewers:
      - "your-username" # Replace with actual username
    commit-message:
      prefix: "⬆️ deps(backend)"
      include: "scope"
    labels:
      - "dependencies"
      - "backend"
      - "automerge"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 5
    assignees:
      - "your-username" # Replace with actual username
    reviewers:
      - "your-username" # Replace with actual username
    commit-message:
      prefix: "⬆️ actions"
      include: "scope"
    labels:
      - "github-actions"
      - "automerge" 