name: 'Setup Test Environment'
description: 'Sets up Node.js and restores dependencies for testing'

inputs:
  node-version:
    description: 'Node.js version to use'
    required: true
  include-playwright:
    description: 'Whether to include Playwright cache'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: 🔧 Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'

    - name: 📦 Cache Dependencies
      id: cache-deps
      uses: actions/cache@v4
      with:
        path: |
          ~/.npm
          frontend/node_modules
          backend/node_modules
          ${{ inputs.include-playwright == 'true' && '~/.cache/ms-playwright' || '' }}
        key: ${{ runner.os }}-node-${{ inputs.node-version }}-${{ hashFiles('**/package-lock.json') }}-playwright-${{ inputs.include-playwright }}
        restore-keys: |
          ${{ runner.os }}-node-${{ inputs.node-version }}-

    - name: 🔨 Install Root Dependencies
      if: steps.cache-deps.outputs.cache-hit != 'true'
      shell: bash
      run: npm ci

    - name: 🔨 Install Frontend Dependencies
      if: steps.cache-deps.outputs.cache-hit != 'true'
      shell: bash
      working-directory: frontend
      run: npm ci

    - name: 🔨 Install Backend Dependencies
      if: steps.cache-deps.outputs.cache-hit != 'true'
      shell: bash
      working-directory: backend
      run: npm ci

    - name: 🎭 Install Playwright Browsers & Dependencies
      if: inputs.include-playwright == 'true' && steps.cache-deps.outputs.cache-hit != 'true'
      shell: bash
      working-directory: frontend
      run: |
        npx playwright install
        sudo npx playwright install-deps 